### ISSUE TITLE
Upgrade to NServiceBus v6

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureStoragePersistence#19]
Task force: @DavidBoike @dbelcham @SeanFeldman @yvesgoeleven

This is the overall epic which incorporates the work for making the Azure Storage Persistence work with core v6.

It includes following subtasks:

- [x] Acceptence Tests https://github.com/Particular/NServiceBus.AzureStoragePersistence/issues/9
- [x] Async/Await support: https://github.com/Particular/NServiceBus.AzureStoragePersistence/issues/14
- [x] Upgrade Azure Storage Dependency to latest major range https://github.com/Particular/NServiceBus.AzureStoragePersistence/issues/21
- [x] Code only configuration API https://github.com/Particular/NServiceBus.AzureStoragePersistence/issues/20
- [x] Update Nuspec https://github.com/Particular/NServiceBus.AzureStoragePersistence/issues/35

**Comment by SimonCropp** [comment]
done
