### ISSUE TITLE
Code only configuration API

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureStoragePersistence#20]
To be consistent with core v6 & the rest of the transports & persistences, we should switch to a code only configuration model on top of SettingsHolder.

Todo: should we provide an overlay for backward compat of xml based config model as well?

Includes following subtasks:

- [x] Remove default connectionstring https://github.com/Particular/NServiceBus.AzureStoragePersistence/issues/3
- [x] Add ability to configure connection string for all persister in a single command https://github.com/Particular/NServiceBus.AzureStoragePersistence/issues/15
- [x] Support NServiceBus/Persistence setting https://github.com/Particular/NServiceBus.AzureStoragePersistence/issues/8

**Comment by yvesgoeleven** [comment]
Replaces https://github.com/Particular/NServiceBus.AzureStoragePersistence/issues/10

**Comment by mikeminutillo** [comment]
Is there anything to on this issue except for #8? #8 is already an issue that is being tracked. This issue has not been updated in 46 days. Is there any value in keeping this one open?

**Comment by WilliamBZA** [comment]
Nope, nothing. Once #8 is in then this is done.
